function [addReinf] = addiReinfBeam (b, h, cover, rebarPhi, rebarQtd, stirPhi)
area = pi*(rebarPhi/2000)^2 ;
d2 = b/2 - cover - (stirPhi/1000) - (rebarPhi/2000);
d25 = d2/2;
d23 = d2/3;
d3 = h/2 - cover - (stirPhi/1000) - (rebarPhi/2000) - 2.5*(rebarPhi/1000);

switch rebarQtd
    case 5
        addReinf = {area + "   " + d2 + "   " + d3 + "   " + area + "   " ...
            + -d2 + "   " + d3 + "   " + area + "   " + -d2 + "   " + -d3 + ...
            "   " + area + "   " + d2 + "   " + -d3};
    case 6
        addReinf = {area + "   " + d2 + "   " + d3 + "   " + area + "   " ...
            + -d2 + "   " + d3 + "   " + area + "   " + -d2 + "   " + -d3 + ...
            "   " + area + "   " + d2 + "   " + -d3 + "   " + area + "   " ...
            + 0 + "   " + d3 + "   " + area + "   "+ 0 + "   " + -d3};
    case 8
        addReinf = {area + "   " + d2 + "   " + d3 + "   " + area + "   " ...
            + -d2 + "   " + d3 + "   " + area + "   " + -d2 + "   " + -d3 + ...
            "   " + area + "   " + d2 + "   " + -d3 + "    " + area + "   " ...
            + d23 + "   " + d3 + "   " + area + "   " + -d23 + "   " + d3 + ...
            "   " + area + "   " + -d23 + "   " + -d3 + "   " + area + ...
            "   " + d23 + "   " + -d3};
    case 9
        addReinf = {area + "   " + d2 + "   " + d3 + "   " + area + "   " ...
            + -d2 + "   " + d3 + "   " + area + "   " + -d2 + "   " + -d3 + ...
            "   " + area + "   " + d2 + "   " + -d3 + "    " + area + "   " ...
            + d25 + "   " + d3 + "   " + area + "   " + -d25 + "   " + d3 + ...
            "   " + area + "   " + -d25 + "   " + -d3 + "   " + area + ...
            "   " + d25 + "   " + -d3};
    case 10
        addReinf = {area + "   " + d2 + "   " + d3 + "   " + area + "   " ...
            + -d2 + "   " + d3 + "   " + area + "   " + -d2 + "   " + -d3 + ...
            "   " + area + "   " + d2 + "   " + -d3 + "    " + area + "   " ...
            + d25 + "   " + d3 + "   " + area + "   " + -d25 + "   " + d3 + ...
            "   " + area + "   " + -d25 + "   " + -d3 + "   " + area + ...
            "   " + d25 + "   " + -d3 + "   " + area + "   " + 0 + "   " + ...
            d3 + "   " + area + "   "+ 0 + "   " + -d3};
    otherwise
        addReinf = {};
end